<?php

namespace AppBundle\Repository;

/**
 * AlbumsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumsRepository extends \Doctrine\ORM\EntityRepository
{
}
