<?php

namespace AppBundle\Repository;

/**
 * BandsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandsRepository extends \Doctrine\ORM\EntityRepository
{
}
