<?php

namespace AppBundle\Repository;

/**
 * Genre_recetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Genre_recetteRepository extends \Doctrine\ORM\EntityRepository
{
}
