<?php

namespace AppBundle\Repository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
    public function nomIngredient() {
        $qb = $this->createQueryBuilder('i')
            ->select('i.nom')
            ->distinct()
            ->getQuery();
        return $qb->getResult();
    }

}
