<?php

namespace AppBundle\Repository;

/**
 * PreparateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreparateurRepository extends \Doctrine\ORM\EntityRepository
{
}
