<?php

namespace AppBundle\Repository;

/**
 * QuantitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantitesRepository extends \Doctrine\ORM\EntityRepository
{
}
