<?php

namespace AppBundle\Repository;

/**
 * Recette_Qte_IngrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Recette_Qte_IngrRepository extends \Doctrine\ORM\EntityRepository
{
}
