<?php

namespace AppBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findInfosByTitle($title)
    {
        $fields = array('r.id', 'r.title', 'r.timePreparation', 'r.timeCuisson',  'r.description');
        return $this->createQueryBuilder('r')
            ->select($fields)
            ->distinct()
            ->andWhere('r.title LIKE :title')
            ->setParameter('title', '%'.$title.'%')
            ->getQuery()
            ->getResult()
            ;
    }


    public function findTitle($title)
    {
        $fields = array('r.title');
        return $this->createQueryBuilder('r')
            ->select($fields)
            ->distinct()
            ->andWhere('r.title LIKE :title')
            ->setParameter('title', '%'.$title.'%')
            ->getQuery()
            ->getResult()
            ;
    }

}
