<?php

namespace AppBundle\Repository;

/**
 * recetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recetteRepository extends \Doctrine\ORM\EntityRepository
{
}
