<?php

namespace AppBundle\Repository;

/**
 * EtapesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapesRepository extends \Doctrine\ORM\EntityRepository
{
}
