<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container41f43v8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container41f43v8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container41f43v8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container41f43v8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container41f43v8\appDevDebugProjectContainer(array(
    'container.build_hash' => '41f43v8',
    'container.build_id' => '271fa8d5',
    'container.build_time' => 1531926951,
), __DIR__.\DIRECTORY_SEPARATOR.'Container41f43v8');
